# Generated by Django 5.2.17 on 2026-10-02 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(choices=[('elementary', 'Elementary'), ('middle', 'Middle school'), ('high', 'High school'), ('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('professional', 'Professional'), ('other', 'Other')], default='other', max_length=20)),
                ('institution', models.CharField(blank=True, default='', max_length=255)),
                ('field_of_study', models.CharField(blank=True, default='', max_length=255)),
                ('preferred_learning_style', models.CharField(blank=True, choices=[('visual', 'Visual'), ('auditory', 'Auditory'), ('reading', 'Reading / writing'), ('kinesthetic', 'Kinesthetic'), ('multimodal', 'Multimodal')], default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['education_level'], name='users_stude_educati_54473e_idx')],
            },
        ),
    ]
