# Generated by Django 5.2.17 on 2026-10-02 20:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('completion_percentage', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='users.studentprofile')),
                ('study_plan_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='plans.studyplanitem')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'status'], name='progress_pr_student_d1e24c_idx'), models.Index(fields=['study_plan_item'], name='progress_pr_study_p_610bbf_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'study_plan_item'), name='unique_progress_per_item')],
            },
        ),
    ]
