# Generated by Django 5.2.17 on 2026-10-02 20:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gaps', '0001_initial'),
        ('resources', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateField()),
                ('target_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='users.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('estimated_minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('learning_gap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_items', to='gaps.learninggap')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_items', to='resources.learningresource')),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plans.studyplan')),
            ],
            options={
                'ordering': ['study_plan_id', 'ordering'],
            },
        ),
        migrations.AddIndex(
            model_name='studyplan',
            index=models.Index(fields=['student', 'status'], name='plans_study_student_8eb2c6_idx'),
        ),
        migrations.AddIndex(
            model_name='studyplanitem',
            index=models.Index(fields=['study_plan', 'status'], name='plans_study_study_p_551260_idx'),
        ),
        migrations.AddIndex(
            model_name='studyplanitem',
            index=models.Index(fields=['study_plan', 'ordering'], name='plans_study_study_p_5c7c7a_idx'),
        ),
        migrations.AddConstraint(
            model_name='studyplanitem',
            constraint=models.UniqueConstraint(fields=('study_plan', 'ordering'), name='unique_plan_item_ordering'),
        ),
    ]
