# Generated by Django 5.2.17 on 2026-10-03 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_runs', '0001_initial'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='agent_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_plans', to='agent_runs.agentrun'),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='origin',
            field=models.CharField(choices=[('manual', 'Manual'), ('agent', 'Agent')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='studyplanitem',
            name='rationale',
            field=models.TextField(blank=True, default=''),
        ),
    ]
