# Generated by Django 5.2.17 on 2026-10-02 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('true_false', 'True / false'), ('short_answer', 'Short answer')], default='multiple_choice', max_length=20)),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.TextField(blank=True, default='')),
                ('explanation', models.TextField(blank=True, default='')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('topic', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessment')),
            ],
            options={
                'ordering': ['assessment_id', 'ordering'],
                'indexes': [models.Index(fields=['assessment', 'ordering'], name='questions_q_assessm_bcc07f_idx'), models.Index(fields=['difficulty'], name='questions_q_difficu_5db314_idx')],
                'constraints': [models.UniqueConstraint(fields=('assessment', 'ordering'), name='unique_question_ordering')],
            },
        ),
    ]
