# Generated by Django 5.2.17 on 2026-10-03 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('remediate_gaps', 'Remediate gaps'), ('refresh_plan', 'Refresh plan')], default='remediate_gaps', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('input_context', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.JSONField(blank=True, default=dict)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='users.studentprofile')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('started', 'Started'), ('gaps_examined', 'Gaps examined'), ('resources_searched', 'Resources searched'), ('resources_evaluated', 'Resources evaluated'), ('plan_built', 'Plan built'), ('report_written', 'Report written'), ('completed', 'Completed'), ('failed', 'Failed'), ('note', 'Note')], max_length=30)),
                ('summary', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agent_runs.agentrun')),
            ],
            options={
                'ordering': ['run_id', 'seq'],
            },
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['student', 'status'], name='agent_runs__student_1f49cf_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['student', '-started_at'], name='agent_runs__student_39e2f6_idx'),
        ),
        migrations.AddIndex(
            model_name='agentevent',
            index=models.Index(fields=['run', 'seq'], name='agent_runs__run_id_c6bc03_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentevent',
            constraint=models.UniqueConstraint(fields=('run', 'seq'), name='unique_event_seq_per_run'),
        ),
    ]
