# Generated by Django 5.2.17 on 2026-10-02 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_index=True, max_length=100)),
                ('topic', models.CharField(db_index=True, max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('source', models.CharField(choices=[('assessment', 'Assessment'), ('manual', 'Manual')], default='assessment', max_length=20)),
                ('evidence', models.TextField(blank=True, default='', help_text='Where this gap was observed (e.g. attempt reference).')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='users.studentprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='gaps_learni_student_da8a45_idx'), models.Index(fields=['student', 'subject'], name='gaps_learni_student_5770e4_idx'), models.Index(fields=['student', 'severity'], name='gaps_learni_student_00b8eb_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'subject', 'topic'), name='unique_gap_per_student_topic')],
            },
        ),
    ]
