# Generated by Django 5.2.17 on 2026-10-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learninggap',
            name='source',
            field=models.CharField(choices=[('assessment', 'Assessment'), ('manual', 'Manual'), ('agent', 'Agent')], default='assessment', max_length=20),
        ),
    ]
