# Generated by Django 5.2.17 on 2026-10-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('url', models.URLField(max_length=2000)),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('book', 'Book'), ('course', 'Course'), ('practice', 'Practice set'), ('interactive', 'Interactive'), ('other', 'Other')], default='article', max_length=20)),
                ('subject', models.CharField(db_index=True, max_length=100)),
                ('topic', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('source_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject', 'topic'], name='resources_l_subject_873aee_idx'), models.Index(fields=['difficulty'], name='resources_l_difficu_92604b_idx'), models.Index(fields=['resource_type'], name='resources_l_resourc_6d17ce_idx')],
            },
        ),
    ]
