# Generated by Django 5.2.17 on 2026-10-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='last_evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='origin',
            field=models.CharField(choices=[('catalog', 'Catalog'), ('web', 'Web'), ('suggested', 'Suggested')], default='catalog', max_length=20),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='quality_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
